### ISSUE TITLE
Chromeでチェックボックスが表示されない

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nako3storage#110]
```
「テスト」のチェックボックス作成。
```
テストは表示されますが、チェックボックスがあるべき場所が空欄で、タッチしてみても反応はなし。
Firefoxや~PCのChrome~では問題ないという謎現象で、~アンドロイドの~Chrome側の問題かと思いきや、簡易エディタや自前のHTMLや貯蔵庫のアプリのページなどでは問題なくて、簡易エディタv2の問題のような？
マニュアルのチェックボックス作成の項のサンプルも同現象でした。
ので、どこにかいたらいいかしらと思いましたが、貯蔵庫にアップした作品であれ？！　ってなったので、とりあえずこちらに。

追記:ちなみに、「チェックボックス作成」で作っても、inputタグを「HTML設定」した場合も同様になります。

追記２:やっぱり、PCのchromeでもなるかも。Edgeでもなるかも。chrome系は全部ダメかも？

**Comment by kujirahand** [comment]
この現象、謎すぎます。。。

nadesi.com/v3/start のエディタだと表示されるのですが、
Firefoxでは表示されるので、chrome固有の減少です。

引き続き調査してみます。

**Comment by kujirahand** [comment]
以下の項目を追加すると直るようです。
```
height: fit-content; 
```

どうやら、ace-editorが悪さしているみたいです。

**Comment by kujirahand** [comment]
貯蔵庫の問題ではなかったことがわかったので、

https://github.com/kujirahand/nadesiko3/issues/1052

にて、対処します。
ご報告ありがとうございます！

暫定対策としては、スタイルに`height: fit-content; `を追加すると直ると思います。

**Comment by snowdrops89** [comment]
ありがとうございます☆
直っていました（≧▽≦）
