### ISSUE TITLE
作品に短いURLでアクセスできるようにする

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nako3storage#12]
mod_rewriteなどでショートURLが適用できるようにする

**Comment by massongit** [comment]
GETメソッドで引数の順番を固定にした場合、以下のようなデメリットがあると考えられます。

* クライアント側から見たとき、引数を指定しづらい (順番に依存しない引数の方が指定しやすい)
* 内部処理において、`$_GET`から直接引数を取れないため組みづらい

そのため、ほとんどのデータをGETメソッドではなくJSON形式で渡す、というのはいかがでしょうか？

**Comment by kujirahand** [comment]
説明不足でした。
作った作品に短いURLでアクセスできるようにするのが目的です。
そのため、ショートカット用のURLを発行するようにすると良いかな？と思いました。

**Comment by kujirahand** [comment]
作品ページの下にショートURLが表示されるようにする
