### ISSUE TITLE
アプリページとエディタページにCSSの差異が大きい

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nako3storage#133]
アプリページとエディタページにCSSの差異が大きい
共通のCSSを使う

**Comment by kujirahand** [comment]
できたら、テーマを選べるようにするのもありかと。

**Comment by snowdrops89** [comment]
テーマが選べるの楽しいですね☆

とりあえずのこととしては、もっとも良くないのが、アプリページでrunboxにtext-align: centerをかけてることですぅ。
文章が全部中央寄せになってしまい、とても見づらくなるんですよよよ。。。
しかも、ブロック要素には効かないので、テーブルは左寄せで表示されるなど、表示が乱れます。
元の表示を維持したまま、幅が狭かった時には中央寄せにする的な感じなら、runboxにtext-alignではなくmargin: autoとwidth: fit-contentを指定するのがいいんじゃないでしょうか。
https://n3s.nadesi.com/widget.php?1744&run=1

あと、エディタページでは、runbox、nako3_div以外に、アプリページには存在しないshowblockとゆうクラスからの継承があり、テーブルやリストやテキストエリアの表示に差が出ています。
https://www.eznavi.net/site/bbs/index2.php?pagetop=1428&cere=3

**Comment by kujirahand** [comment]
とりあえず、n3s.nadesi.comにrunboxをfit-contentにする件、反映してみました。
テーマは、どうやって実装するか #134 で対応しようと思います。
@snowdrops89 さん、ご指摘と、修正方法に感謝です！
