### ISSUE TITLE
投稿した素材を描画ダウンロードや描画データURL変換できない

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nako3storage#140]
サンドボックス化した影響なのかなと思うのですが、貯蔵庫にアップロードした素材に対して、プログラム編集中は出来るのですが、投稿すると描画ダウンロードや描画データURL変換が出来なくなります。

これとか、
https://n3s.nadesi.com/id.php?539
これ。
https://n3s.nadesi.com/id.php?1020

画面上は無反応で、コンソールに
```
Uncaught DOMException: The operation is insecure.
```
が出ます。
貯蔵庫が外部サイト扱いになって、セキュリティエラーになっているんだと思うのですが。

**Comment by kujirahand** [comment]
おぉおぉ。。。確かに。ご報告ありがとうございます。

解決方法は2つ。

- [1] Sandboxの制限を緩くする
- [2] ユーザーのプログラム内で、URLを読み込む際に「https://n3s.nadesi.com」があれば「https://n3s-sandbox.nadesi.com/」に置換して実行する

まずは、[1]案で。

**Comment by kujirahand** [comment]
おや？しかし、image.php では `access-control-allow-origin: *`を指定しているので、
クロスドメインでの画像編集は問題ないはず・・・
現に、CSVファイルやなでしこ本の特典15パズルはn3s.nadesi.com/image.phpは問題なく動くようです。

それで、エラーメッセージ`The canvas has been tainted by cross-origin data.`で調べて見ると・・・やはり、外部URLの画像をキャンバスに描画した場合に生じる問題のようです。
解決方法は、画像を読み込んだ際に、`img.crossOrigin = "Anonymous";`のようなコードを足すことだそうです。

(参考) https://stackoverflow.com/questions/22097747/how-to-fix-getimagedata-error-the-canvas-has-been-tainted-by-cross-origin-data

とりあえず、「画像読んだ時」を使わずに、JS実行などで画像を読み込んで、imgにcrossOrigin='Anonymous'を付けると解決するそうです。

将来的には、なでしこ側のコードにこのプロパティを付ければ、他のも動くようになるかな？

**Comment by snowdrops89** [comment]
おお～！　JS実行で`img.crossOrigin = "Anonymous";`付けたらできました！！！
https://n3s.nadesi.com/id.php?1777
画像処理もできました☆

普通に表示したりは出来るんですがtoDataURLとかgetImageDataしようとすると出る的なやつのようですね。
それで、実は、マニュアルのエディタでは、画像描画などのサンプルは貯蔵庫にアップロードした画像を使って出来るのですが、描画ダウンロードや描画データURL変換のサンプルはできなかったんです～。
貯蔵庫の外だからしょうがないね！　と思ってたんですが、なでしこの命令側でこの対応が出来たら、もしかするとマニュアルでもできるようになるかも？

**Comment by snowdrops89** [comment]
できるようになってましたね🎊 
マニュアルの簡易エディタ２でも無事できました☆
ありがとうございました！
