### ISSUE TITLE
限定公開キーあり限定公開作品の、キー入力時の遷移先

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nako3storage#141]
キーを設定しなければ、一覧には表示されませんがURLを知っていれば見ることが出来る感じになるのですが、キーを設定すると、「以下にキーを入力してください」の画面にキーを入力しても、同じ画面が入れ子状に出続けて、閲覧できないようです。

追記：閲覧できないというか実行できなくなるが正解でした。
正しいキーを入れるとページは表示されて、エディタにコードも入るのですが、その下に実行ボタンが表示されず、投稿 **** は非公開です。の画面が入ってしまいます。
https://n3s.nadesi.com/index.php?action=show&page=1780&editkey=yukino

**Comment by kujirahand** [comment]
いやはや、盲点でした。テストしてくださり感謝です！

**Comment by snowdrops89** [comment]
確認しました‼️
ありがとうございます💕

**Comment by snowdrops89** [comment]
あっっ＞＜
スミマセン。OKだと思ったんですが、よく考えると・・・

1. この作品のURL: https://n3s.nadesi.com/id.php?1780

　の場合は直ったのですが、

2. アプリ(即時実行)のURL: https://n3s.nadesi.com/widget.php?1780&run=1
3. アプリ(実行ボタンあり)のURL: https://n3s.nadesi.com/widget.php?1780&editkey=yukino

　アプリページの場合にも１と同じ、エディタのついた表示になってしまっています～。

**Comment by snowdrops89** [comment]
そしてなんと！
ログイン状態で自分が投稿した限定公開の作品を開いた場合、アプリの実行画面が入るはずのフレームの中に、エディタが入れ子状に入ります～（＠＿＠）
スクロールすれば、フレームの中のエディタの下には実行ボタンがあって実行はできますし、「作品を編集」ボタンを押して、編集ページは問題ないのでそんなには困らないのですが；；；
こうなる～～～。
![無題](https://user-images.githubusercontent.com/59927104/186565943-9039622f-d627-44ee-9d8e-9c81d3919667.jpg)

**Comment by snowdrops89** [comment]
#146 の対応をしていただいたことで分かったのですが、「投稿 1780 は非公開です。」とキー入力を促す画面で、submitした時の遷移先が、閲覧の場合は「 https://n3s.nadesi.com/index.php?action=show&page=1780&editkey=yukino 」そして編集の場合は「 https://n3s.nadesi.com/index.php?action=edit&page=1780&editkey=yukino 」とそれぞれ固定になっているんですよね。

しかし、アプリページを開こうとした場合にも、同じキー入力画面が出ますが、アプリページの場合の遷移先は、即時実行の場合は「 https://n3s-sandbox.nadesi.com/index.php?action=widget_frame&page=1780&run=1&mute_title=1&editkey=yukino 」、実行ボタンありの場合は「 https://n3s-sandbox.nadesi.com/index.php?action=widget_frame&page=1780&mute_title=1&editkey=yukino 」と、それぞれ異なるところへ遷移しなきゃいけないのではないでしょうか。

そして、ログインしてマイページから限定公開の作品を開いた時が一番カオスなんですが、エディタとフッター部分の間のフレームに、このキー入力画面が表示され、キーを入れるとエディタの下にエディタが！　となるのは上でも書いたとうりなのですが、ここで、編集の方でキーを入れ、フレームの中の方で編集をして上書きを押そうものなら、「ログインが必要」とかいわれてしまうのですぅ＞＜（フレームの内側のエディタには、ログイン状態が反映されてないっぽい）
タブンこのフレームには、実行ボタンありのアプリページへ遷移が正解なんじゃないでしょうか。
そしてできればマイページからの場合はキー入力なしでしゅっと開いてほしいです。

**Comment by kujirahand** [comment]
修正が甘かったようで、すみません。
こちら、キー入力後に、あるべきところへ戻るように修正しました！

**Comment by snowdrops89** [comment]
ありがとうございます！！！

ああぁ、でも、即時実行の時のrun=1が反映されて無くて、実行ボタンありと同じになってしまうようです～。
細かくてスミマセン・・・＞＜

**Comment by kujirahand** [comment]
あ、確かに！ご報告ありがとうございます😊

**Comment by kujirahand** [comment]
run=1の件修正しました！

**Comment by snowdrops89** [comment]
確認しました☆
ありがとうございます！（≧▽≦）
