### ISSUE TITLE
ログオフ状態で投稿した作品が、編集キーを入れても再編集できるようにならないみたい？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nako3storage#146]
先ほどちょっと試してみたら、編集キーを入れても元の画面に戻ってしまい再編集できないようなんです・・・
https://n3s.nadesi.com/index.php?action=show&page=1796&editkey=yukino

たぶん、
https://n3s.nadesi.com/index.php?action=edit&page=1796&editkey=yukino
に遷移するのが正解だと思うのですが・・・

 誰も何も言わないからずっと前からとゆうことは無いと思うのですが、もしかすると #141 の修正時に何かが・・・？

**Comment by kujirahand** [comment]
26c566e104311822158bde5c9f35f24bc13dce21 で修正しました。この後、反映したいと思います。

**Comment by snowdrops89** [comment]
再編集できるようになりました！ありがとうございます☆

が・・・
#141 に追記した件に関連して、ログイン状態でキーありで限定公開した作品の画面が一段とカオスな感じになっちゃいましたよよよ・・・
こちらは閉じて、そっちに書きます～。
