### ISSUE TITLE
「最新の投稿」が公開順になるとうれしい

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nako3storage#158]
https://www.eznavi.net/site/bbs/index2.php?pagetop=1511&cere=3

　現在は、「最新の投稿」は、保存された番号順となっているので、下書き保存のつもりで非公開で保存してプログラムを作成し、日が経ってから完成した作品を公開すると、すでに新着じゃ無くなっている場合があるんですよね。
　下書き的な意味合いでは一時保存もありますが、スマホとか他の端末から動作確認をしたりちょこっと修正したりするためには、やはり貯蔵庫上に保存したいので、わたしの場合は公開する時には新規に保存し直しています。
　公開順や、最終編集日時順のソートができるようになったり、できればトップの最新の投稿は公開順になっているとうれしい感じです。

　あとこれについて考えてて気づいたんですが、プログラムの「投稿日時」の後ろの「編集」の日時って、何の日時なんでしょうか。最終編集日時なのかと思いきや、投稿日時よりも（だいぶ）前の日付になっているんです～。
　タブン投稿日時は、最初の保存した日時で、トップページの一覧で説明の後に付記されている日付が最終編集日時ですよね。
　公開の投稿になった日時は、特に管理されてない感じなのでしょうか。

**Comment by kujirahand** [comment]
提案ありがとうございます！
リストの表示順を、最終編集日時に変更するように修正してみます。

**Comment by kujirahand** [comment]
あっ、でも、これだと公開順にはなりませんね。
ただ、投稿を更新すると最新投稿に表示されるというのは、良いことかもです。

**Comment by snowdrops89** [comment]
ありがとうございます～☆
更新されたものが上がってくるシステムも良いのですが、ちょうど昨日、去年のアドベントカレンダー用だったワタシの投稿に、タグを付けまくっていたんですよね～。あわわわわって感じになっててビックリしました😅本来の最新の投稿をほとんど追い出してしもうた💧・・・とゆう事件が起こりますｗ
なので、自動的に表示されるトップページは公開順で、他に更新順とかでのソート機能があると便利そうなのですが（個人の感想；）
でも「公開の投稿になった日時」が管理されてないと、公開順には出来ないんですよね～。

**Comment by kujirahand** [comment]
とりあえず良さそうなので一度閉じますね！ありがとうございます。
