### ISSUE TITLE
エラーで投稿画面の作品が動作しなくなっています

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nako3storage#164]
編集画面では動作しますが、投稿画面のサンドボックスでは、実行ボタンを押しても動作せず、
```
Uncaught TypeError: document.querySelector(...) is null
```
のようなエラーがコンソールに出ています。
発生はv3.4.10になってだと思うのですが、なでしこの利用バージョンはv3.4.5で作成したものが動作せず、3.3.71までもどしてやっと動作しました。

**Comment by kujirahand** [comment]
この問題、ブレイクポイントボタンの取得に失敗していました。
以下のコミットで修正しました。
926a2cecb518f4410cb815150d1eb7ec82d5ac12

**Comment by snowdrops89** [comment]
確認しました☆
早速ありがとうございます！
