### ISSUE TITLE
プラグインを取り込む、取り込まないを選択できるようにする

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nako3storage#29]
デフォルトではとりあえず全部のプラグインを取り込みます。

しかし、取り込むプラグインを選びたい時に、取り込むJavaScriptを指定できるようにします。
例えば、最低限のプラグインのみ取り込みたい場合、下記のように指定します。

```
<!-- 最低限だけ取り込む -->
<script defer src="https://nadesi.com/v3/cdn.php?v=3.1.19&f=/release/wnako3.js"></script>
<script defer src="https://nadesi.com/v3/cdn.php?v=3.1.19&f=release/plugin_turtle.js"></script>
```

セキュリティの問題で、現状は以下のURLにマッチするスクリプトのみ取り込めます。

```
https://nadesi.com/v3/cdn.php?xxx
https://cdn.jsdelivr.net/npm/chart.js@xxx
```

**Comment by kujirahand** [comment]
とりあえず、プラグイン取り込み用のカスタムヘッダ領域を追加します。

**Comment by yy0931** [comment]
ページを開いただけで任意のスクリプトが実行されるため、セキュリティ的にまずいと思います。たとえば投稿を見ただけでその投稿を見たユーザーの権限で新しいプログラムを投稿/削除するとかができてしまいます。特定のパターンのみ許可するようにしませんか。

**Comment by yy0931** [comment]
https://nadesi.com/v3/storage/id.php?464
このように取り込み文で取り込むのはどうですか。今の実装だと `https://nadesi.com/v3/cdn.php?v=3.1.19&f=/release/wnako3.js` の拡張子が.phpとして判定されてしまうため、content-typeで判定するか、取り込み文に拡張子を指定する文法を追加する必要があります。

**Comment by kujirahand** [comment]
> ページを開いただけで任意のスクリプトが実行されるため、セキュリティ的にまずいと思います。
> たとえば投稿を見ただけでその投稿を見たユーザーの権限で新しいプログラムを投稿/削除するとかができてしまいます。

こちらですが、既にCRSF対策してあるので、JSから投稿することは不可能と思います。
ref: #51

> 特定のパターンのみ許可するようにしませんか。

とは言え、こちらは賛成です。

**Comment by yy0931** [comment]
CSRFタグがあっても、scriptタグで読み込んだスクリプトはoriginが閲覧中のサイトと同じになるため、投稿することはできると思います。
参考: https://stackoverflow.com/questions/28527641/whats-the-origin-of-an-embedded-script

**Comment by kujirahand** [comment]
＠yy0931 さん、その通りですね。早めに対策を入れたいと思います。

**Comment by kujirahand** [comment]
こちら、やはりよくないと思いますので、機能を廃止したいと思います。

**Comment by kujirahand** [comment]
#75 で機能を廃止しました。
