### ISSUE TITLE
リソースをアップロードする仕組み

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nako3storage#3]
プログラムだけでなく、その他のリソースも保存できるようにする。
プログラムから利用したファイルをアップロードできるようにする。

**Comment by massongit** [comment]
参考までに。
* [PHP/クライアント側のバイナリデータをPHPで取得する方法 - PapuuWiki](http://papuu.jp/wiki/index.php?PHP%2F%A5%AF%A5%E9%A5%A4%A5%A2%A5%F3%A5%C8%C2%A6%A4%CE%A5%D0%A5%A4%A5%CA%A5%EA%A5%C7%A1%BC%A5%BF%A4%F2PHP%A4%C7%BC%E8%C6%C0%A4%B9%A4%EB%CA%FD%CB%A1)

**Comment by kujirahand** [comment]
著作権的に問題のあるアップロードがあるかもしれないので
アップロードされた素材を、一覧で確認して、非公開設定する管理画面が必要

**Comment by kujirahand** [comment]
また、アップロード素材は、
画像：JPEGとPNG、GIFなど画像ファイル
テキストデータ：CSV、JSON、テキスト
と制限をかける
最大アップロードサイズも3MBなどに制限する

**Comment by kujirahand** [comment]
とりあえず画像だけ対応
