### ISSUE TITLE
素材のアップロードがうまく出来ない感じ？

### ISSUE THREAD

**Issue by snowdrops89** [kujirahand/nako3storage#52]
jpegなんですけれど・・・
```
アップロード失敗
画像や音声、テキスト形式のファイルのみアップロードできます。 ()
```
となってしまいます。
なにか、他に制限があるでしょうか？
サイズ的には60KB程度のものなのですが。
いちおう、ファイル名を半角アルファベットに直してみたりしてみましたが、変わらずでした。

**Comment by kujirahand** [comment]
@snowdrops89 さん、
報告ありがとうございます。
先日データベース関連のアップデートしたときの修正が不完全でした。
現在、アップロードできるようになりました。
もう一度、よろしくお願いします。

**Comment by snowdrops89** [comment]
できました！！
早速、ありがとございます（≧▽≦）
