### ISSUE TITLE
WebWorkerを使うプログラムがUnsafeと表示される

### ISSUE THREAD

**Issue by kujirahand** [kujirahand/nako3storage#59]
呼び出し側と同じドメインではないのでエラーとなる気がする。

```
Unsafe attempt to load URL
```

**Comment by weyk** [comment]
動かすとこうなります。

セキュリティエラー: https://nadesi.com/v3/storage/id.php?483 のコンテンツが https://cdn.jsdelivr.net/npm/nadesiko3@3.1.21/release/wnako3webworker.js からデータを読み取ることは禁止されています。
MIME タイプ (“text/html”) が許可されていないため、“https://nadesi.com/v3/cdn.php?v=3.1.21&f=release/wnako3webworker.js” からの Worker の読み込みがブロックされました。

後者は
> Strict MIME type checks
という機能のようです。 constructorと importScripts()の両方ともあります（IE未サポート？）

前者に、以下が影響する可能性があります。constructorにはimportScriptsを書いたDataURLを渡しているためです。
Note: that there is a disagreement among browser manufacturers about whether a data URI is of the same origin or not. Though Gecko 10.0 (Firefox 10.0 / Thunderbird 10.0 / SeaMonkey 2.7) and later accept data URIs, that's not the case in all other browsers.

以下のページのコンテンツセキュリティポリシー参考。
https://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by kujirahand** [comment]
Unsafeと出る問題は修正しましたが、まだなにかエラーが出ていますね。。。

**Comment by weyk** [comment]
nako3storageに登録していた、WebWorkerの試行プログラム、修正しました。
試行プログラムの規模でもエラーを修正してゆくのが大変なので、WebWorker周りに補強が必要かも。

**Comment by kujirahand** [comment]
@weyk さん、確認ありがとうございました。
こちら閉じますね。
